### ISSUE TITLE
refresh subject list every time we go to step 4

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#103]
If you have 2 browsers open, browser 1 is at step 2, browser 2 creates a new subject, the new subject does not show up in the subject list when browser 1 proceeds to step 4. Let's fix it so that every time you go to step 4, you get the most up to date subject list. We can get directed to step 4 from step 2 or step 5, so let's make sure both work this way.

@olehkorkh-planeks this is a bit urgent - could we have it done in the next few days? We need this feature by friday.

**Comment by suhlrich** [comment]
This works as described. A slight change. Can we query /subjects/ every time they click on the dropdown button? 

The use case is that a subject get's created on another machine while you're in step 4. We want that subject to show up on the list.
@olehkorkh-planeks

**Comment by suhlrich** [comment]
I think this works. Have a look @olehkorkh-planeks https://github.com/stanfordnmbl/opencap-viewer/pull/117

**Comment by antoinefalisse** [comment]
@suhlrich closing this one, please re-open if needed.
