### ISSUE TITLE
need to clear cookies to get updated web app

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#145]
users are reporting needing to clear their cookies to get updated versions of the web app. For example, after pushing this update https://github.com/stanfordnmbl/opencap-viewer/pull/141, a user who had been using the app prior to the update didn't get it until clearing cookies.

Thoughts @olehkorkh-planeks @anastasiiadidan @AlbertoCasasOrtiz @antoinefalisse

**Comment by AlbertoCasasOrtiz** [comment]
Maybe we could just show a toast message for a week or so, asking users to clear their cookies, as we did in the past to ask users to update the mobile app.

Or we could add a button to the login page to clear cookies. This is related to what I mentioned at some time of "forgetting my user info" in shared computers.

**Comment by antoinefalisse** [comment]
don;t think this is still an issue, closing.
