### ISSUE TITLE
Show time on visualizer

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#170]
Could we display timestamps on the visualizer? Similar to the OpenSim GUI?
@AlbertoCasasOrtiz is that something you could add to a coming sprint?

**Comment by AlbertoCasasOrtiz** [comment]
I am not sure what timestamps are you referring to. Can you share a screenshot?

**Comment by antoinefalisse** [comment]
When you play a motion in OpenSim, you see the timestamp next to the progress bar:

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/39206704-1b83-42c9-ad28-c018419be45f)

In OpenCap, we only see the progress bar. This is annoying if you want to do post-processing analysis where you need to specify what time window to analyze, as you then need to first play the motion in the OepnSim GUI.

It is not a super top priority, just something to keep in mind. But if it is easy to display the time stamp next to the progress bar, that would be great.

**Comment by AlbertoCasasOrtiz** [comment]
I think that would be easy since we have the number of frames and the frames per second.
