### ISSUE TITLE
Sessions to big to download

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#174]
Users are complaining about not being able to download sessions with many (many) trials.
Two options:
- We bump up the celery workers (again)
- We display a warning message pointing to the colab

I would go for option 2 with a threshold of 20 trials.
Thoughts @suhlrich?

**Comment by suhlrich** [comment]
agreed. If 20 seems like a reasonable limit.

Scott Uhlrich, PhD
Director of Research | Human Performance Lab
Bioengineering Department
Stanford University
<https://nmbl.stanford.edu/people/scott-uhlrich/>website<https://nmbl.stanford.edu/people/scott-uhlrich/>
________________________________
From: Antoine Falisse ***@***.***>
Sent: Monday, July 10, 2023 9:56 AM
To: stanfordnmbl/opencap-viewer ***@***.***>
Cc: Scott David Uhlrich ***@***.***>; Mention ***@***.***>
Subject: [stanfordnmbl/opencap-viewer] Sessions to big to download (Issue #174)


Users are complaining about not being able to download sessions with many (many) trials.
Two options:

  *   We bump up the celery workers (again)
  *   We display a warning message pointing to the colab

I would go for option 2 with a threshold of 20 trials.
Thoughts @suhlrich<https://github.com/suhlrich>?
