### ISSUE TITLE
Add 2 more compliance checkboxes

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#201]
- [x] When user is creating an account, let's add three mandatory check boxes before they can create the account 
1) "I confirm that I have read and agree to the Terms and Conditions of OpenCap." Links:  (link https://www.opencap.ai/terms-conditions)
2) "I confirm that I have read and agree to the the Privacy Policy of OpenCap." Link:  (https://docs.google.com/document/d/1DBw9LVAuUwgz713037VQjsaD8sj2-AN_hzga_7kXtXI)
3) "I confirm that I am using OpenCap for academic or non-profit organization non-commercial research or educational use only and that my use of OpenCap is in compliance with the relevant privacy, security, and human subjects research regulations in my location."
- [x] When a new subject is created for the first time (will have to add this to both places where a subject is created [session list and Step4]), add a mandatory checkbox that says:
Header: The participant must read and complete this section:
Text: "I, the research Participant, have provided informed consent to the research Investigator conducting this study. I have read and I agree to the Terms and Conditions and Privacy Policy of the OpenCap tool." Links:  (link https://www.opencap.ai/terms-conditions; https://docs.google.com/document/d/1DBw9LVAuUwgz713037VQjsaD8sj2-AN_hzga_7kXtXI)

**Comment by antoinefalisse** [comment]
For 2, I would use the same language as in the terms and conditions:

I confirm that I am using OpenCap for academic or non-profit organization non-commercial research or educational use only and that my use ...

**Comment by antoinefalisse** [comment]
Closed with #219
