### ISSUE TITLE
Step 5 authentication

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#205]
When a session is public and you are not logged in, you see: 
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/43877159/2f6ec044-cf5a-4c9e-aad1-d1e22dfdb1c6)
If you are logged in and it is not your session, you see the limited version without the record bar (see below). This is correct and it is what you should see in a public session if you are not logged in.
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/43877159/987e83e4-b6d8-492d-80c2-0cbc1399edeb)

**Comment by olehkorkh-planeks** [comment]
@suhlrich @antoinefalisse 
I prepared two PRs with fixes:

Backend - https://github.com/stanfordnmbl/opencap-api/pull/126
Frontend - https://github.com/stanfordnmbl/opencap-viewer/pull/235
