### ISSUE TITLE
Sessions to display in session list

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#209]
Users complain that their sessions disappear, this might happen when they try to reprocess things locally and it fails. All the trials are then `error`, and their session disappears from the list. I suggest that in addition to our criteria, we display sessions if there is at least one dynamic trial even if it is `error`

**Comment by AlbertoCasasOrtiz** [comment]
This was an error in the api, we were filtering sessions in the api so sessions with no neutral trials done are omitted. Solved in opencap-api dev.
