### ISSUE TITLE
Change names of steps to something more meaningful

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-viewer#231]
I've noticed we are still using "Step n" names in code an URLs.

Should we change it to names more meaningful? For example, Step 1 could be "connect_phones", Step 2 could be "calibration" and Step 4 could be "neutral pose".

I think it could be confusing having in the URLs Step 1, Step 2 and Step 4, when Step 3 is not used, and Step 5 is session view.

**Comment by RogueCode007** [comment]
Hello @AlbertoCasasOrtiz , I'd love to contribute. Can I work on this ?

**Comment by AlbertoCasasOrtiz** [comment]
@RogueCode007 Sure! Let me know if you have any doubt about it.

**Comment by AlbertoCasasOrtiz** [comment]
@antoinefalisse @suhlrich Before start with this one, we should decide new names for the steps. Here are some initial proposals:

Step1 -> device-synchronization or device-setup?
Step2 -> calibration-trial-record?
Step3 -> (We should directly remove this one, right?)
Step4 -> neutral-trial-record?
