### ISSUE TITLE
Y Quantities go into graph when multiple

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#236]
@olehkorkh-planeks could you please fix what is described in the image such that the Y Quantities do not go into the graph. Thanks.

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/4ce70677-84cc-41bf-82f9-b194bc21f426)

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse Check the fix - https://github.com/stanfordnmbl/opencap-viewer/pull/237
