### ISSUE TITLE
Cannot record new trial after renaming one in step 5

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#242]
After you rename a trial in step5, the start recording button does nothing. Error message in the console is:

TypeError: this.$refs.observer.validate is not a function
    changeState Step5.vue:733

**Comment by olehkorkh-planeks** [comment]
Fix - https://github.com/stanfordnmbl/opencap-viewer/pull/244/files

**Comment by antoinefalisse** [comment]
This is fixed, but I noticed that core crashes if you rename the trial while it is being processed. We should block rename if trial status == 'processing' and throw an api error: 'Sorry this trial is being processed by the server so cannot be renamed right now. Please rename once processing is complete'.

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse I did it in a bit different way. Added some improvement to the dialog - https://github.com/stanfordnmbl/opencap-viewer/pull/247/files

https://share.cleanshot.com/RcSkp1GP3CRwMmxq99Kv

Let me know if it is OK

**Comment by suhlrich** [comment]
Thanks @olehkorkh-planeks. Two problems after testing:

1) it seems like if any trial is uploading or processing, renaming any other trial is blocked. See video.
https://drive.google.com/file/d/1Abjj3XouOH1QfiogQm2mRvFeufoukLi_/view?usp=sharing

2) on some trials the dialog closes right when you click in the box to rename. but not for others. unclear why. Sometimes it seems like this is the second time you try to rename something, but it isn't consistently that.
https://drive.google.com/open?id=1Abpk2AzT8ZTnlNq186NmlntC6xxgUhDT&usp=drive_fs

**Comment by olehkorkh-planeks** [comment]
@suhlrich Please, check this PR https://github.com/stanfordnmbl/opencap-viewer/pull/251/files
