### ISSUE TITLE
Sync videos

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-viewer#26]
In #3, we discovered that using v-for to render the videos was causing the videos to not be synchronized. Now, we only have two video elements instead of an v-for generating as many video elements as needed.

We need to find an optimal way of showing as many videos as needed synchronized.

**Comment by antoinefalisse** [comment]
We reverted some changes, since we prefer showing all videos even if not well synced the first time we play them. So the issue how can we keep the v-for and have everything synced.

**Comment by suhlrich** [comment]
the third video now does not play at all.

**Comment by antoinefalisse** [comment]
It plays the second time...
