### ISSUE TITLE
Implement Subject Level Tags

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-viewer#278]
Description is here: https://docs.google.com/presentation/d/1S5DOuoe1W7DeShV52XTnWFWIr8QjMr0xCB1EpcDRu0k/edit#slide=id.g26632e15046_0_5

For the trial tags, one approach could be to add to the (already existing) meta entry at the trial level. At the moment, it is only used to keep track of errors on core, to bring them back to the frontend for display. But I don't see a reason not to use it for something else. We will just want to make sure that we are not overwriting what is in. Thoughts @suhlrich

**Comment by AlbertoCasasOrtiz** [comment]
In order to avoid problems related to overwriting data, make it easier to query subjects/trials using the tags, and have a better structured database. I am creating new tables for tags.

Right now, the subject level tags are almost implemented. We could test it in isolation and then proceed to implement trial level tags.

Regarding session level tags, I don't thing it is going to be necessary, since we can assume a session tag's is the intersection of tags of its trials/subjects.

**Comment by antoinefalisse** [comment]
Feedback:

- [ ] Add unimpaired at the very top of the list
- [ ] Should get red error when creating subject without tag, for now it just does not let you go through

**Comment by AlbertoCasasOrtiz** [comment]
@antoinefalisse Everything here should be fixed. The only thing is that the two 'ss' in the admin console are because the name of the table is 'subject tags', and it adds automatically an s to every table name to indicate plural (for example, for table 'User', it adds the s to indicate the table contains 'Users' in plural).

**Comment by antoinefalisse** [comment]
Would it make sense to have subject tag then?

**Comment by AlbertoCasasOrtiz** [comment]
That would solve it, but would also require migrating the database since one of the tables is changing name.

**Comment by antoinefalisse** [comment]
Okay, let's keep as is. It's not a big deal.

**Comment by AlbertoCasasOrtiz** [comment]
New issues found by @antoinefalisse:

 - [ ] In the database, the tag _unimpaired_ is saved as _healthy_, should be the same in both.
 - [ ] If you select a tag and then click outside of the `New Tag` popup, the full popup is closed, not only the tag selection element.
 - [ ] If you select a tag, and then clear the tags, you would be able to create a subject without tags (with should not be allowed since it is not an optional field).
   - Probably is checking if by default it is none or undefined, and when you insert something and then clear, it is an empty list, thus it is not none or undefined.
 - [ ] If you populate the popup and then create a subject, when you try to create a new one the info is not cleared.
 - [ ] Review error message for tags field.
 - [ ] Move it to the mandatory section.

**Comment by AlbertoCasasOrtiz** [comment]
@antoinefalisse I think everything should be working now.

For the `In the database, the tag unimpaired is saved as healthy, should be the same in both.` issue, I just modified the json to be consistent. Now every tag labeled as unimpaired will be saved as unimpaired in opencap. The final public json file should be corrected, and this issue should be addressed in the addbiomechanics side, not in the opencap side.

**Comment by antoinefalisse** [comment]
Thanks, will try to get to thtat this week.
