### ISSUE TITLE
Upgrades gait analysis

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#283]
@olehkorkh-planeks Two requests

1. Add info about analysis, I suggest adding a ? next to the analysis name with some info when hovering mouse on it (see first screenshot). We could type the info in the django admin console.

2. Add info about scalars/metrics. I suggest adding a pop-up box with some text that would appear when hovering mouse over title (see second screenshot). Ideally we don't need to add a ? button so that we do not make things busier on the frontend. The text should be retrieved from the json from the lambda function (one piece of text per scalar/metric).

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/de306a64-761a-49e0-b48f-57cebe0cabc4)

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/ad35dfe8-066e-40a9-b127-0d8cb7bdb2a1)

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse I prepared the PRs:

Frontend - https://github.com/stanfordnmbl/opencap-viewer/pull/290
Backend - https://github.com/stanfordnmbl/opencap-api/pull/167

You can add an optional "info" attribute to the "metrics" section in a function response.

https://share.cleanshot.com/cNSZYVWVS3psMtJtFHRd

In that case, you'll see the info icon and a tooltip on the dashboard.

https://share.cleanshot.com/xm3Z5C4ZxGS1W95f1cCD

Also, you can add the function info in the admin.

https://share.cleanshot.com/WG5LDKdgl8xxG2sFWhP3

It is optional. But if the info field has some content, you'll see the info icon on the dialog.

https://share.cleanshot.com/GxVrcDypSvgMLZkCFNXB
