### ISSUE TITLE
Inserting wrong password shows error [Object object] instead of something more informative

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-viewer#287]

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz I am now getting this. Could we return a more informative error? Thanks

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/0e0277e6-796d-43f3-8660-91a0db9819b4)

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz we also get a weird error when the username does not exist. Thanks.

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz I am still have the error above when inserting the wrong password or a non existing username
