### ISSUE TITLE
Updates analysis

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#296]
- [x] Add option to make analysis public such that it can be shared via the URL. Let's add a button on the frontend, similar to [step5](https://github.com/stanfordnmbl/opencap-viewer/blob/main/src/components/pages/Step5.vue#L290).

- [x] @olehkorkh-planeks is there a way to fix the order of the scalar values on the analysis dashboard. It is not ideal that it is always a different order in the [scalarplot](https://github.com/stanfordnmbl/opencap-viewer/blob/main/src/components/ui/ScalarPlot.vue). Could we add indices to the scalars and sort by indices? Eg, 0_gait_speed, 1_cadence, etc? Or something like that?

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse A partial update with fixing scalar plot ordering:

https://github.com/stanfordnmbl/opencap-viewer/pull/325

**Comment by antoinefalisse** [comment]
Thanks @olehkorkh-planeks, the second task is tested and merged.

**Comment by olehkorkh-planeks** [comment]
Hi @antoinefalisse, There are the pull-requests for sharing public analysis:

Backend - https://github.com/stanfordnmbl/opencap-api/pull/187/files
Frontend - https://github.com/stanfordnmbl/opencap-viewer/pull/336/files

**Comment by antoinefalisse** [comment]
@olehkorkh-planeks thanks it works as expected. However, we cannot have the analyses from all public sessions available to the person who receives the link. Here is a use case. A doctor sends a link to a patient with their analyses (different trials from a session). To do that, the doctor has to make the session public, which is fine. However, we do not want the patient to have access to analyses from another patients, which would be possible with the current implementation. I understand that it is tricky given how the analysis dashboard page is implemented. Do you have any ideas about how sharing could be limited to only the analyses from the shared session?

Another piece of feedback, which might not be relevant depending on how you solve the above. When you click on share analysis publicly, you get a link. But this will only work if the session is public. We should add some logic there. If the session is not yet public, then add a box that says: "Make session public" with a ? that says "To make your analysis public, you need to make your session public". We should then also add a ? on the session side next to Make session public that says "Making your session public will make your analysis public too".

Let me know for questions.

**Comment by olehkorkh-planeks** [comment]
Hi @antoinefalisse 

> Here is a use case. A doctor sends a link to a patient with their analyses (different trials from a session). To do that, the doctor has to make the session public, which is fine. However, we do not want the patient to have access to analyses from another patients, which would be possible with the current implementation. I understand that it is tricky given how the analysis dashboard page is implemented. Do you have any ideas about how sharing could be limited to only the analyses from the shared session?

OK. I see that we need to generate and use some additional URL parameter for specifying which exact data we want to make accessible. How do you think, can we generate a unique URL for the subject level. In that case, the user will be able to open the link and see only public sessions and trials related to the particular subject. In that case, the Subject select will have only single option. Or maybe we need to generate unique URL for the session? Or for the trial?

Let me know your thoughts.

> Another piece of feedback, which might not be relevant depending on how you solve the above. When you click on share analysis publicly, you get a link. But this will only work if the session is public. We should add some logic there. If the session is not yet public, then add a box that says: "Make session public" with a ? that says "To make your analysis public, you need to make your session public". We should then also add a ? on the session side next to Make session public that says "Making your session public will make your analysis public too".

Yes, it will be more clear for user. I'll add that feature.

**Comment by antoinefalisse** [comment]
@olehkorkh-planeks if you generate a URL for the subject, then when you share it from an analysis, will it point to that analysis specifically and then the user can select another public session/trial from the dropdown menu? I think it is important that the URL points to exactly what the sender wants the user to see. So in other words, how would the URL differentiate between an analysis made on 2024-04-30 and 2024-05-25 for instance? If that's possible, then yes I think it is what we want: a URL that points to the analysis, and then the option for the receiver to open the other public sessions from that subject only (and all private sessions if the receiver is signed in and the subject belongs to them).

Also, another piece of feedback. Currently, if you open an analysis through the dashboard list, then it does not retain the id, which is a problem for sharing:

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/841a1784-193a-4650-8707-79f64155923d)

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse 
> if you generate a URL for the subject, then when you share it from an analysis, will it point to that analysis specifically and then the user can select another public session/trial from the dropdown menu?

Yes. I can add the proper `trialId` parameter for the currently selected trial.

> So in other words, how would the URL differentiate between an analysis made on 2024-04-30 and 2024-05-25 for instance?

As I understand, ther will be two separate trials. Correct? So, we'll be able to generate URLs that will point diretly to the analysis for the proper trials.

> Also, another piece of feedback. Currently, if you open an analysis through the dashboard list, then it does not retain the id, which is a problem for sharing

You're right. We can use `history.pushState` for adding the proper `trialId` paramater when trial selects.

I also improve the sharing with adding extra parameters, like subject id and a some generated token. The backend will verify the token and returns the data for the proper subject.
