### ISSUE TITLE
In register page, use a dropdown with existing countries, so users do not type fake contries.

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-viewer#30]

**Comment by antoinefalisse** [comment]
Closed with #51

**Comment by nileshtrivedi** [comment]
Actually, `vue-country-dropdown` package no longer exists on NPM. https://www.npmjs.com/package/vue-country-dropdown

**Comment by nileshtrivedi** [comment]
Since this is a security vulnerability, I created [this issue](https://github.com/opencap-org/opencap-viewer/issues/530).
