### ISSUE TITLE
Let people change their email address

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#337]
@AlbertoCasasOrtiz people currently need to ask us to change their email address, could we allow them to change that through their profile? Thanks.

**Comment by AlbertoCasasOrtiz** [comment]
Sure, I think that is a good idea.

Is this a priority I should work during the current spring, or is it something we could add to the next one?

**Comment by antoinefalisse** [comment]
Let's add to next sprint, thanks.
