### ISSUE TITLE
Subject and session loading Admin

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#342]
@olehkorkh-planeks do you have any thoughts?

When logged-in as admin, the web app is lagging because it tries to load data from all session/subjects belonging to all opencap users. 

This is related to these lines on the api side:
- sessions: https://github.com/stanfordnmbl/opencap-api/blob/main/mcserver/views.py#L166
- subjects: https://github.com/stanfordnmbl/opencap-api/blob/main/mcserver/views.py#L1668

Having access to all sessions/subjects is however needed on the core side, because we "run" core using the admin token and need to retrieve session info and subject info from the trial being processed:
- sessions: https://github.com/stanfordnmbl/opencap-core/blob/main/utils.py#L364
- subjects: https://github.com/stanfordnmbl/opencap-core/blob/main/utils.py#L397

Could we optimize things on the frontend side such that not everything is being loaded? I believe you did something similar to optimize speed previously. While it is only a problem for admin at this stage, this might become a problem from actual users who have a lot of data.

Here is a video that describes what is happening:

https://drive.google.com/file/d/1ImUu9p2xL4-WfOBT9yHFlvgqZRPJwh_y/view?usp=sharing

**Comment by olehkorkh-planeks** [comment]
Backend - https://github.com/stanfordnmbl/opencap-api/pull/198/files
Frontend - https://github.com/stanfordnmbl/opencap-viewer/pull/347/files

**Comment by antoinefalisse** [comment]
Hi @olehkorkh-planeks,I am still having issues. It says no data available. The console reports some network errors. This all seems related to the subject tags we recently added. It works fine for non-admin users, probably because users have fewer subjects. Let me know if there is anything I can do to help you fix this (eg, give you access to admin account).

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/45b513a7-599d-4eed-ab4d-c2a63fa4cb3f)
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/4b789f63-dda8-4a13-8fe6-4ee4d09a72d0)

**Comment by olehkorkh-planeks** [comment]
Hi @antoinefalisse Yes, I need to research it. Please, provide me your access credentials. I need an access to the account (including admin). I'm also thinking that maybe I'll need to download the dump of the database for local tests. If it is possible, I need to check it as well. Because, maybe, we'll need some more radical architecture changes for the frontend.

**Comment by antoinefalisse** [comment]
- [ ] Date format
- [ ] Filtering by session name, subject name, number of trials does not seem to work
- [ ] Not getting QR code
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/824cf25c-c7eb-4272-8255-f469b5916eb9)

- [ ] not loading session (step5)
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/cc18b5fd-6d6c-40bc-bc6b-df96b10e5902)

- [ ] logout error (probably not a new one, I saw this in console)
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/50095595-70ab-468e-9d08-89cd10a6a19c)

**Comment by antoinefalisse** [comment]
@olehkorkh-planeks two more small bugs:

- [ ] No data available shows up for a fraction of second when you click on dropdown
- [ ] Subjects get edited without needing to save, mandatory fields can be left empty

see [this video](https://drive.google.com/file/d/1KOKiDzFCSobFK90P07SWdcJwen_j0MLH/view?usp=sharing) for details.
