### ISSUE TITLE
When adding a new subject, they are not automatically selected

### ISSUE THREAD

**Issue by carmichaelong** [stanfordnmbl/opencap-viewer#355]
This happened often, though some opencap operators noted that it may have been an intermittent issue (i.e., that sometimes it may have been automatically selected).

**Comment by antoinefalisse** [comment]
@carmichaelong and @AlbertoCasasOrtiz this should be fixed with latest PR. Let's monitor and close if not happening anymore.

**Comment by antoinefalisse** [comment]
@carmichaelong and @AlbertoCasasOrtiz closing this one as I think it is done.
