### ISSUE TITLE
Feature request: Show a loading bar on phones with uploading checkerboard calibration videos

### ISSUE THREAD

**Issue by carmichaelong** [stanfordnmbl/opencap-viewer#363]
User requested this as a way to help give them information when debugging a setup that is failing during calibration.

Like when uploading patient videos, it could be helpful to show the loading bar to help users find which device may be having trouble uploading during this step.

**Comment by antoinefalisse** [comment]
Let's double check, but it should be what is happening. It is just very fast

**Comment by antoinefalisse** [comment]
@carmichaelong and @AlbertoCasasOrtiz closing this one as I think it is done
