### ISSUE TITLE
Delete subject returning error but working

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#388]
Subject page: If you trash a subject, then click on Show Removed Subjects, then try to delete the trashed subject, you get an error:

![image](https://github.com/user-attachments/assets/eaa247fd-8bdb-48bf-a145-132701b4ef83)

However, if you refresh, the subject has been deleted.

**Comment by AlbertoCasasOrtiz** [comment]
This should be solved in [this PR](https://github.com/stanfordnmbl/opencap-api/pull/220) of the AP. However, the PR is too big, so I am taking some time to review it before doing merge.
