### ISSUE TITLE
 Need action (refresh or clicking something) for restore to appear at trial level

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#391]
If you have already selected "Show Removed Trial", then you need to refresh to get the option to hit restore. If you haven't yet selected that option, then clicking "Show Removed Trial" "acts as refresh" and you get the option to select restore.

@AlbertoCasasOrtiz could you try to reproduce? Is that something you could address? No big rush.

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz can you take a look? I can assign to Planeks if you like, just let me know.

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse PR - https://github.com/stanfordnmbl/opencap-viewer/pull/397/files

I found the same issue on other page, so I tried to fix it globally. As I realized, `v-if` works unreliable for combination of menu item and `v-dialog`.

**Comment by antoinefalisse** [comment]
Solved with #397
