### ISSUE TITLE
If trial is trashed, then you can name a new trial with same name

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#398]
If a trial has been trashed, then you can record a new trial and name it with the same name as the trashed trial. This creates problems if you then want to for instance retrieve the trial ID using the API, since it might return the ID of the trashed trial.

- [x] Prevent naming a trial with the same name as a trashed trial. This should only be possible if the trial has been deleted (ie, no longer existing in the db)

See this example where we have twice DVJ1:

![image](https://github.com/user-attachments/assets/26a1cbf6-cc93-4195-aa49-db68bcc512f3)

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse https://github.com/stanfordnmbl/opencap-viewer/pull/402/files

**Comment by antoinefalisse** [comment]
@olehkorkh-planeks thanks your fix is working. I noticed something related, you can rename a trial with the name of an already existing trial. Could you please make sure you cannot rename with the name of (1) an existing trial and (2) a trashed trial? Thanks.

![image](https://github.com/user-attachments/assets/e78145b9-3762-44c3-825a-fc6435a9bc09)

**Comment by antoinefalisse** [comment]
@olehkorkh-planeks I delete my previous comment. I adjusted as I wanted and this is all good.
