### ISSUE TITLE
Updates - landing page

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#52]
- [x] The number of trials should be the number of trials seen on the visualizer screen - we should exclude calibration trials and failed neutral trials to avoid confusion.
- [x] Let's reformat the date/time. Instead of for instance `2022-12-13T17:21:58.053996Z` let's have `2022-12-13`.

@suhlrich and @AlbertoCasasOrtiz, would you include failed trials in the number of trials?

**Comment by AlbertoCasasOrtiz** [comment]
Yeah, I agree. Since neutral is shown in the list of trials, I think we should include it.

Maybe we should use this issue to fully review the sessions list page. I remember we had a conversation about changing the date format to something more human readable too.

**Comment by antoinefalisse** [comment]
Yes, that is a good idea.

**Comment by antoinefalisse** [comment]
I updated the issue description
