### ISSUE TITLE
Session from "New session, same setup" not displayed in session list

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#55]
@AlbertoCasasOrtiz and @suhlrich sessions collected after clicking on the "New session, same setup" button are NOT displayed in the session list. Users are complaining about data being lost. Can we make this a priority?

Here is an example for the admin account:
- "Parent session": [474ce909-62a7-422b-94cf-e8f2becba894](https://api.opencap.ai/sessions/474ce909-62a7-422b-94cf-e8f2becba894/)
- "Child session": [39b39b22-4a3d-453b-8b92-d4137dfb7be7](https://api.opencap.ai/sessions/39b39b22-4a3d-453b-8b92-d4137dfb7be7/)

**Comment by AlbertoCasasOrtiz** [comment]
Copied from Slack:

> I am checking the code and in opencap-viewer, we are calling to the API url /sessions/valid/
> 
> https://github.com/stanfordnmbl/opencap-viewer/blob/2f1eced578a82f7f517fe21072e434854965b659/src/store/data.js#L121
> 
> Then in the API, /sessions/valid is pointing to SessionViewSet.valid(). Here, we are checking that for a session to be valid, the number of trials must be greater than or equal 3.
> 
> https://github.com/stanfordnmbl/opencap-api/blob/9cb21f1fb695b488b82a4556aa582e222d547760/mcserver/views.py#L180
> 
> When users complaining about this issue clicked on "New Session, Same Setup", did they recorded more than 3 trials? If not, according to this it shouldn't show.

Conclusion after Zoom meeting:

> Currently, a session is considered valid if it has at least 3 trials (`neutral`, `calibration`, and an arbitrary `successfully capture trial`).
> 
> However, when clicking on "New Session, same setup", the `calibration` trial is not present, and the case of a valid session with just two trials is possible.
> 
> Also, it could be possible that users create a session with same setup as another session, and only create the `neutral` trial (maybe with the idea of recording the rest of the trials later, or there could be an error that takes the user out of the session page).
> 
> So, a session should be valid if:
> 
> - It has at least 1 trial, and
> - one trial is the `neutral` trial, and
> - the status of the `neutral` trial is `done`.
