### ISSUE TITLE
Show more informative errors

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-viewer#73]
Current errors are a little cryptic sometimes, showing [Object object] instead of the real message.

**Comment by AlbertoCasasOrtiz** [comment]
Cases found while testing the app:
 - Server is down: Error(s) Occurred: Network Error
 - Incorrect credentials: Error(s) Occurred while logging in: Unable to log in with provided credentials. Bad Request (400) - Maybe we should address the reason of the error?
 - Email not found when recovering password: Error(s) occurred while sending the password recovery email.: detail: Not Found. HTTP status: Not Found (404).
- Confirm in step 3 if there is no calibration data: Error(s) occurred: [object Object[ HTTP status: Internal Server Error (500)
- Record in step 3 if there is no calibration data: Error(s) occurred: [object Object[ HTTP status: Internal Server Error (500)
- Create a trial in frontend that is not created in backend: Error(s) occured: TpeError: Cannot read proeprties of undefined (reading 'trials').

**Comment by antoinefalisse** [comment]
Reverted changes, issue re-opened.
