### ISSUE TITLE
permanently delete trial in Step 5

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#74]
Currently, you can only recycle a trial from step 5, which means you can't "re-record" a trial that is bad, since it will get an auto-incremented number. I propose we have an option to permanently delete a trial in the "remove" pop-up. If you click permanently remove, you get another "are you sure" pop up.

Thoughts, @antoinefalisse @AlbertoCasasOrtiz

**Comment by AlbertoCasasOrtiz** [comment]
I think that is a good idea. It should be easy. I am not sure how the trial name autoincrement works, but I guess that after removing a trial with a given name, you should be able to create a new one without "_1" at the end.

**Comment by suhlrich** [comment]
After removing (aka recycling) a trial, the next trial you record gives auto-incrementation. This makes sense since autoincrement just looks at trials in database, regardless of whether they have delete flag. If you permanently delete (by going to the trashcan), it does not auto-increment.

We could change the logic for autoincrement: only query non-recycled trialnames. But if we do this, they could restore the trial and have multiple trials with same name which could mess up logic down the road. That's why I propose a permanent delete solution.

**Comment by antoinefalisse** [comment]
@anastasiiadidan and @olehkorkh-planeks, we would like to add the possibility to permanently delete a trial from the screen where users record trials (we call it step5). The motivation is to keep auto-increment number working. Right now, if you record a trial and name it "test", then you can record the next trial under the same name and it will automatically be named "test_1", and then "test_2", etc. If you remove a trial (eg "test_2") that goes to the recycle bin, then your list is something list "test", "test_1", "test_3", etc (missing "test_2"). By allowing users to permanently delete trials, they will have a nice list of trial names.

Here is a proposed implementation. When users click on remove, they get a pop-up window (as is now) but with the added option to also permanently delete the trial:

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/53e4448c-e8b8-4ef9-b3f9-95df2553c739)

If they click on yes for permanent remove, then they get another pop-up window asking if they are sure.

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/69e63129-b52b-4bef-8f1e-e268b2cc3bb5)

If they click on yes, then the trial is permanently removed.

Let us know for any questions.

**Comment by anastasiiadidan** [comment]
@antoinefalisse I'd suggest to rename current `Remove` option to `Trash` instead and add `Remove` as permanent remove option to trial's actions list. We can have a popup for the new `Remove` with a message, e.g. `Do you want to permanently remove trial? This action cannot be undone!` and initiate action after user clicks `Yes`. Having 2 separate remove options may help users to navigate easier, but having all in one popup may confuse them.
Let me know if it makes sence.

**Comment by antoinefalisse** [comment]
Yes, this sounds better. Please then change `Remove` to `Trash` everywhere else. Same for `Show Removed ...` => `Show Trashed ...`. Let's use `Delete` instead of `Remove`. For the `Delete` message, let's have `Do you want to permanently delete trial <trial_name>? This action cannot be undone. Use Trash to keep the ability to restore the trial`.

**Comment by antoinefalisse** [comment]
Closed with #153
