### ISSUE TITLE
Weird behaviour on remove menus.

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-viewer#76]
How to reproduce:

- Click on any `menu` and click on `Remove...`
- Click **outside** of the pop up twice (**do not click on Yes or No**), to make the Remove window and the menu disappear.
- Repeat these steps **multiple time**s. Sometimes the menu will appear and sometimes it will not.

This happens in every menu I've tried. with both `Restore...` and `Remove...`

**Comment by AlbertoCasasOrtiz** [comment]
This is in main, so you should be able to replicate it on the deployed version in prod. Basically, If you exit the popup and the menu clicking outside of the box and you try to open it again, the popup does not appear, and you have to try again several times for it to appear.


https://user-images.githubusercontent.com/15672785/231025126-6a9a37cd-79a3-4ec7-851e-fa59a52af7e9.mp4

**Comment by antoinefalisse** [comment]
@olehkorkh-planeks, whenever you have some time, it looks like there is a minor issue with the Remove button. Thanks.

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse OK, I will check it

**Comment by antoinefalisse** [comment]
Closed w/ #90
