### ISSUE TITLE
Number of connected phones

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#79]
The number of connected phones creates problems in calibration and neutral that we do not give good error messages for.

Problems:
P1) you could only use 1 phone and get all the way thru neutral. You get a sync error at neutral (not intuitive).
P1.5) you could connect 3 phones, and only 2 are talking to the server (ie only 2 video instances get created in the trial). You would get all the way to Step 5 without knowing.
P2) At calibration or neutral, n phones connected to the session, and <n videos are uploaded. Trial `status=stopped` waiting for upload. Will say "trial is processing" on front end forever (15 min, until dequeue in API turns to error). Only way out is refresh. This is likely why we have so many 'stopped' but not uploaded trials on server (there's no way to cancel on Step2/4).

Minimum behavior:
P1) Error immediately after calibration is stopped.  I implemented this thru backend (https://github.com/stanfordnmbl/opencap-core/commit/123270a9c5b8020fb1f9fd5244d3f65707f847f3), but we may want to move this nCamerasConnected logic to frontend and API given other problems. My backend solution does not solve P1.5.
P2) Calib and neutral: error the trial after some max upload time (eg 60s) if not all videos have not uploaded. 

Useful behavior:
We've discussed an indicator of number of cameras connected and haven't done it b/c we thought we'd have to log in the database every time a unique phone pinged the session. There's an easier and almost as good way to do this:

Viewer side: Every time you stop a trial, in the top right, some text would say "devices connected: #,\n videos uploaded: #". We could leave the "devices connected" value up from the last recorded trial and remove "videos uploaded" once the state changes from uploading.
API: The `calibration_img` (Step 2), `neutral_img` (Step 4), and `status` (Step 5) endpoints of Session view set would return the number of video instances created for the trial (`numDevicesConnected`; number of phones that pinged the server at any time during the recording), and the number of video instances with a link in the "video" field (`numUploadedVideos`). The viewer would update the numbers each time these endpoints are queried.

If we do this: 
P1 can be solved on the viewer side (or we can leave it on backend)
P1.5 would not get a hard error, but people could check the number of connected phones at calibration
P2 Viewer can start a timer for how long (60s) it is willing to stay in upload state (ie `numUploadedVideos<numPhones`). Just setting a timer after end of recording can't tell if the videos didn't upload, or if they did upload and you're waiting in a processing queue. It could also save `nPhonesCalibration` from Step 2, and check `numDevicesConnected<numPhonesCalibration` to solve https://github.com/stanfordnmbl/opencap-viewer/issues/78 without any logic on API.

Thoughts @antoinefalisse, @AlbertoCasasOrtiz?

**Comment by antoinefalisse** [comment]
Great. How about adding a "devices expected #" too? This would be based on the number of devices used for calibration and would help catching when the phones are freezing (as you said) or dying (low battery maybe)

**Comment by suhlrich** [comment]
I like that. Devices expected in Steps 4 and 5

**Comment by suhlrich** [comment]
Here's a better defined task list.

**new/modified API endpoints**:

- [ ]  new: `sessions/<session_id>/get_n_calibrated_cameras`: find the most recent calibration trial, return the number of video instances
- [ ] modify `sessions/<session_id>/get_status`: for the most recent trial:
    - if status == recording, find number of video instances created -> `n_cameras_connected`. Default=None
    - if status == uploading, find the number of video instances with a link in the 'video' field -> `n_videos_uploaded`. Default=0.
    - add `n_cameras_connected` and `n_videos_uploaded` to the result json
- [ ] modify `sessions/<session_id>/calibration_img`: if status == processing, add `n_cameras_connected` and `n_videos_uploaded` to result, using logic described above. Will need to add these results to other cases in this endpoint, with defaults as described above.
- [ ] modify `sessions/<session_id>/neutral_img`: same logic as `sessions/<session_id>/calibration_img`

- [ ] **Step 2:**
- nothing different before clicking record
- after the recording has finished, get the two new camera variables from `sessions/<session_id>/calibration_img` and display them in a new "block" as in the image below. 
- if `n_cameras_connected` == 1, throw this error: "Only 1 camera connected to the session and 2+ cameras are required, please re-pair cameras using qr code at top of page."
- If there is an error, the cameras block stays where it is, and does not update until the recording has finished again (when `sessions/<session_id>/calibration_img` is queried)

- [ ] **Step 4**:
- nothing different before clicking record
- once the recording is finished:
    - query `sessions/<session_id>/get_n_calibrated_cameras` one time to get `n_calibrated_cameras`
    - get the two other camera variables each time `sessions/<session_id>/neutral_img` is queried and update them in a new "block" as in the image below. 
    - If there is an error, the cameras block stays where it is, and does not update until the recording has finished again (when `sessions/<session_id>/calibration_img` is queried)

**Step 5**:
- when first landing on the page, populate the nCameras box based on data from the neutral trial. Save the values from Step 4 and populate the 'cameras calibrated' and 'cameras connected' fields from this data. Do not show the 'videos uploaded field' yet.
- When a trial is recording, update the 'cameras connected' field if it from the results of `sessions/<session_id>/get_status` if it is different from the current value.
- When `sessions/<session_id>/get_status` returns status == 'uploading', show the 'videos uploaded' field and populate it with the `n_videos_uploaded` value returned by that query.
- When `sessions/<session_id>/get_status` returns status == 'ready', remove the 'videos uploaded' field
- Only show the cameras connected box if someone navigated to Step 5 from Step 4, or if they have completed a recording on Step 5. This way it doesn't show up when we are just visualizing old sessions.

Step 2
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/43877159/17e6d4b1-5198-4c51-81c3-2d09a892ef5f)

Step 4
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/43877159/9a1633de-9d36-4412-8b85-0a94bd0d26f2)

Step 5
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/43877159/94744c28-312b-4665-a0d8-dc2df9cbdcde)

**Comment by antoinefalisse** [comment]
Do we need to display the three lines or could we 1) internally have the sanity check cameras calibrated vs cameras connected and display an error message if they do not match and 2) have a single line: videos uploaded: x / y where y is the # of connected cameras and x is the number of uploaded videos. Just trying to make things simpler and avoid adding stuff to the FE. I think we might confuse users with calibrated vs connected.

**Comment by suhlrich** [comment]
brilliant. will update.

**Comment by suhlrich** [comment]
@AlbertoCasasOrtiz, I tested this on dev. It is awesome! Thanks much for putting it together. A few things from my test:

- [ ] step4: let's move it to the right above the instructions instead of left panel. Also, can we shrink the height of the box?
- [ ] step 4: when you hit new session same setup from step 5, it shows x/0 cameras. In this case, it should look to the parent session's (sessionWithCalibration in the metadata) calibration trial to find nCameras.
- [ ] step 5: the nCameras uploaded stays at 0 despite the http request returning a different number. For example, I disconnected a phone and it said 0/3 uploaded, despite the http request showing that 2 were uploaded.

Otherwise, great!

**Comment by AlbertoCasasOrtiz** [comment]
@suhlrich Thank you for testing!

step4: Sure, I can move the it to right and try shrinking the height of the box. It should be easy.
step4: Good find. I did it in a way that it should be looking into the chain of parents until one with a calibration trial is found, maybe I forgot about something.

step 5: I will test this and fix!

**Comment by AlbertoCasasOrtiz** [comment]
I did a demo today during the dev demos meeting and I got some feedback about showing the num. connected phones and everything more clearly and verbose.

**Comment by antoinefalisse** [comment]
Nice, what do you want to change?
