### ISSUE TITLE
Problem creating new users when already signed in.

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#8]
See details here: https://github.com/stanfordnmbl/opencap-viewer-private/issues/209

**Comment by AlbertoCasasOrtiz** [comment]
@suhlrich, @antoinefalisse I've been thinking about this issue and I think a quick solution that could save headaches to users trying to create an account while another user is logged in would be this:

 - If no user is logged in and an user goes to /register/, allow to register normally showing the register form.
 - If an user is logged in and an user goes to /register/, do not show the register form and show a message instead, maybe something like this: "Please, log out before creating a new one."

**Comment by suhlrich** [comment]
what if we just log out whenever someone navigates to the page if they're logged in? @AlbertoCasasOrtiz @antoinefalisse

**Comment by AlbertoCasasOrtiz** [comment]
@suhlrich That could work too and I think would be a better solution, I do not think anyone would "accidentaly" navigate to register since we do not link to it anywhere in any logged in page. And if this happens, that person would only have to login again.
