### ISSUE TITLE
Session name

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#91]
Now that we have the nice subject feature, there's no real way to identify a given session for a subject. E.g., for analyzing the same person many times, I'd want to select th person, then name the session "week1" or something. 

I suggest we make an optional `session_name` field in Step 4 and add it to metadata of the session. The session list could also display this name.

Thoughts @antoinefalisse , @AlbertoCasasOrtiz

**Comment by AlbertoCasasOrtiz** [comment]
Maybe I can take this one for the next sprint.

In summary we want to:
1. Add a new field "session_name" to the session metadata in the database.
2. Set "session_name" from step 4.
3. Allow to edit "session_name" from the sessions list in the frontend from a new "Rename..." option in the menu.

Is this correct? Only thing I have doubts is if "session_name" should be part of the metadata, or a field in the "Session" tables. Setting it in the metadata should be easier (we do not have to migrate), but maybe it would be more convenient to have it as a table field (faster to retrieve? I am not sure). Let me know what do you think.

**Comment by suhlrich** [comment]
This sounds good. I'm ok with it as metadata, but if it is better practice to have it as a field in the Session model, that's ok too. I'll leave it up to you.

**Comment by AlbertoCasasOrtiz** [comment]
Found a small bug here. When you rename a session and the new name is loaded in the table, the date format changes.
