### ISSUE TITLE
Impossible to change name of trial if name is too long

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-viewer#98]
If you rename the trial to something longer, it is not possible to access to the menus, so you cannot remove or rename the trial.

![Capture](https://user-images.githubusercontent.com/15672785/236319056-ca78fd38-9f3c-4329-a052-c0d9e3517210.PNG)

**Comment by antoinefalisse** [comment]
Great fix @AlbertoCasasOrtiz thanks
